package sn.ucad.entites;
// Generated 16 avr. 2018 11:31:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name = "classe", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "libelle_classe"))
public class Classe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "codeclasse", unique = true, nullable = false, length = 254)
	private String codeclasse;
	//@JsonBackReference(value="3")
	//@JsonIgnoreProperties
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codedepartement", nullable = true)
	@JsonIgnore
	private Departement departement;
	@Column(name = "libelle_classe", unique = true, length = 254)
	private String libelleClasse;
	@Column(name = "nombree_etudiant")
	private Integer nombreeEtudiant;
	//@JsonManagedReference
	//@JsonIgnoreProperties
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classe")
	private Set<Promotion> promotions = new HashSet<Promotion>(0);

	public Classe() {
	}

	public Classe(String codeclasse, Departement departement) {
		this.codeclasse = codeclasse;
		this.departement = departement;
	}
	public Classe(String codeclasse, Departement departement,String libelleClasse,Integer nombreeEtudiant) {
		this.codeclasse = codeclasse;
		this.departement = departement;
		this.libelleClasse = libelleClasse;
		this.nombreeEtudiant = nombreeEtudiant;
	}

	public Classe(String codeclasse, String libelleClasse, Integer nombreeEtudiant) {
		super();
		this.codeclasse = codeclasse;
		this.libelleClasse = libelleClasse;
		this.nombreeEtudiant = nombreeEtudiant;
	}

	public Classe(String codeclasse, Departement departement, String libelleClasse, Integer nombreeEtudiant,
			Set<Promotion> promotions) {
		this.codeclasse = codeclasse;
		this.departement = departement;
		this.libelleClasse = libelleClasse;
		this.nombreeEtudiant = nombreeEtudiant;
		this.promotions = promotions;
	}

	
	public String getCodeclasse() {
		return this.codeclasse;
	}

	public void setCodeclasse(String codeclasse) {
		this.codeclasse = codeclasse;
	}
	
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	
	public String getLibelleClasse() {
		return this.libelleClasse;
	}

	public void setLibelleClasse(String libelleClasse) {
		this.libelleClasse = libelleClasse;
	}

	
	public Integer getNombreeEtudiant() {
		return this.nombreeEtudiant;
	}

	public void setNombreeEtudiant(Integer nombreeEtudiant) {
		this.nombreeEtudiant = nombreeEtudiant;
	}
	
	public Set<Promotion> getPromotions() {
		return this.promotions;
	}

	public void setPromotions(Set<Promotion> promotions) {
		this.promotions = promotions;
	}

}
