package sn.ucad.entites;
// Generated 16 avr. 2018 11:31:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Departement generated by hbm2java
 */

@Entity
@Table(name = "departement", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "libelledepartement"))
public class Departement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "codedepartement", unique = true, nullable = false, length = 254)
	private String codedepartement;
	//@JsonBackReference(value="10")
	//@JsonIgnoreProperties
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codefaculte", nullable = true)
	@JsonIgnore
	private Faculte faculte;
	@Column(name = "libelledepartement", unique = true, length = 254)
	private String libelledepartement;
	//@JsonManagedReference
	//@JsonIgnoreProperties
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	private Set<Classe> classes = new HashSet<Classe>(0);

	public Departement() {
	}

	public Departement(String codedepartement, Faculte faculte) {
		this.codedepartement = codedepartement;
		this.faculte = faculte;
	}
	
	public Departement(String codedepartement, Faculte faculte, String libelledepartement) {
		this.codedepartement = codedepartement;
		this.faculte = faculte;
		this.libelledepartement = libelledepartement;
	}

	public Departement(String codedepartement, Faculte faculte, String libelledepartement, Set<Classe> classes) {
		this.codedepartement = codedepartement;
		this.faculte = faculte;
		this.libelledepartement = libelledepartement;
		this.classes = classes;
	}

	
	public String getCodedepartement() {
		return this.codedepartement;
	}

	public void setCodedepartement(String codedepartement) {
		this.codedepartement = codedepartement;
	}
	
	public Faculte getFaculte() {
		return this.faculte;
	}

	public void setFaculte(Faculte faculte) {
		this.faculte = faculte;
	}

	
	public String getLibelledepartement() {
		return this.libelledepartement;
	}

	public void setLibelledepartement(String libelledepartement) {
		this.libelledepartement = libelledepartement;
	}
	
	public Set<Classe> getClasses() {
		return this.classes;
	}

	public void setClasses(Set<Classe> classes) {
		this.classes = classes;
	}

}
