package sn.ucad.entites;
// Generated 16 avr. 2018 11:31:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", schema = "public")
public class Etudiant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "numeroetudiant", unique = true, nullable = false, length = 254)
	private String numeroetudiant;
	//@JsonBackReference(value="4")
	@JsonIgnoreProperties
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "annee", nullable = true)
	@JsonIgnore
	private Promotion promotion;
	@Column(name = "nom", length = 254)
	private String nom;
	@Column(name = "prenom", length = 254)
	private String prenom;
	@Column(name = "email", length = 254)
	private String email;
	@JsonManagedReference
	@JsonIgnoreProperties
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	private Set<Note> notes = new HashSet<Note>(0);

	public Etudiant() {
	}

	public Etudiant(String numeroetudiant, Promotion promotion) {
		this.numeroetudiant = numeroetudiant;
		this.promotion = promotion;
	}
	public Etudiant(String numeroetudiant, Promotion promotion, String nom, String prenom, String email) {
		this.numeroetudiant = numeroetudiant;
		this.promotion = promotion;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
	}

	public Etudiant(String numeroetudiant, String nom, String prenom, String email) {
		super();
		this.numeroetudiant = numeroetudiant;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
	}

	public Etudiant(String numeroetudiant, Promotion promotion, String nom, String prenom, String email,
			Set<Note> notes) {
		this.numeroetudiant = numeroetudiant;
		this.promotion = promotion;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.notes = notes;
	}

	
	public String getNumeroetudiant() {
		return this.numeroetudiant;
	}

	public void setNumeroetudiant(String numeroetudiant) {
		this.numeroetudiant = numeroetudiant;
	}
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	public Set<Note> getNotes() {
		return this.notes;
	}

	public void setNotes(Set<Note> notes) {
		this.notes = notes;
	}

}
