package sn.ucad.entites;
// Generated 16 avr. 2018 11:31:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Faculte generated by hbm2java
 */
@Entity
@Table(name = "faculte", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "libellefaculte"))
public class Faculte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "codefaculte", unique = true, nullable = false, length = 254)
	private String codefaculte;
	@Column(name = "libellefaculte", unique = true, length = 254)
	private String libellefaculte;
	//@JsonManagedReference(value="6")
	//@JsonIgnoreProperties
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faculte")
	private Set<Departement> departements = new HashSet<Departement>(0);

	public Faculte() {
	}

	public Faculte(String codefaculte) {
		this.codefaculte = codefaculte;
	}
	public Faculte(String codefaculte,String libellefaculte ) {
		this.codefaculte = codefaculte;
		this.libellefaculte = libellefaculte;
	}

	public Faculte(String codefaculte, String libellefaculte, Set<Departement> departements) {
		this.codefaculte = codefaculte;
		this.libellefaculte = libellefaculte;
		this.departements = departements;
	}

	
	public String getCodefaculte() {
		return this.codefaculte;
	}

	public void setCodefaculte(String codefaculte) {
		this.codefaculte = codefaculte;
	}

	
	public String getLibellefaculte() {
		return this.libellefaculte;
	}

	public void setLibellefaculte(String libellefaculte) {
		this.libellefaculte = libellefaculte;
	}
	
	public Set<Departement> getDepartements() {
		return this.departements;
	}

	public void setDepartements(Set<Departement> departements) {
		this.departements = departements;
	}

}
