package sn.ucad.entites;
// Generated 16 avr. 2018 11:31:36 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", schema = "public")
public class Note implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "codenote", unique = true, nullable = false, length = 254)
	private String codenote;
	//@JsonBackReference(value="7")
	@JsonIgnoreProperties
	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "numeroetudiant", nullable = true)
	private Etudiant etudiant;
	//@JsonBackReference(value="8")
	//@JsonIgnoreProperties
	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "codeevaluation", nullable = true)
	private Evaluation evaluation;
	@Column(name = "note")
	private Integer note;

	public String getCodenote() {
		return codenote;
	}

	public void setCodenote(String codenote) {
		this.codenote = codenote;
	}

	public Note() {
	}

	public Note(String codenote, Etudiant etudiant, Evaluation evaluation, Integer note) {
		this.codenote = codenote;
		this.etudiant = etudiant;
		this.evaluation = evaluation;
		this.note = note;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Evaluation getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(Evaluation evaluation) {
		this.evaluation = evaluation;
	}

	public Integer getNote() {
		return this.note;
	}

	public void setNote(Integer note) {
		this.note = note;
	}

}
